### ISSUE TITLE
Feature request :- Tracking Hotspot 

### ISSUE THREAD

**Issue by ghost** [itsdrnoob/DataMonitor#264]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the Feature you'd like

Add the option of hotspot limit and tracking in the application and notify when the limit is completed.

### Why do you want this feature?

This feature is more useful when we give a hotspot to a friend just for a little help, but after getting the hotspot he starts downloading videos.
