### ISSUE TITLE
Meta - enclose checklist in an <details> accordian tag

### ISSUE THREAD

**Issue by killerrook** [itsdrnoob/DataMonitor#70]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Is your feature request related to a problem? Please describe.

The checklist is pretty long and repetitive, monotonous, and eye sore when going through lots of issues

### Describe the solution you'd like

Decluttering by using details accordian tag 

### Additional context

- Even if this is not achievable to do in the issue template, this can be done using the bot - similar to the one implemented for auto-resizing the images
- the checklist accordian need not be open by-default, since presence of unchecked items is shown clearly in the github issue UI - and knowing that some "task" is not done, the interested person can easily open the details accordian
<img alt="Screenshot_2022-11-09-17-09-14-82_79bc5d99886106bfc3f2688bf01a61d3" src="https://user-images.githubusercontent.com/19423063/200182620-42af4c25-1a28-4601-91a3-263fc1c6580e.png" />

**Comment by itsdrnoob** [comment]
> The checklist is pretty long and repetitive, monotonous, and eye sore when going through lots of issues

It's just 3 options, why collapse it?

**Comment by killerrook** [comment]
> It's just 3 options, why collapse it?

Page looks a little bit cleaner would also be useful if you decide to add more things like i checked faq, etc.

**Comment by itsdrnoob** [comment]
> Page looks a little bit cleaner

But for the person opening an issue, they might completly miss the checklist due to the reason that it is collapsed, and will be unable to submit the issue.

**Comment by killerrook** [comment]
Collapse after the issue is created using bot or use asterisk* mark which will prevent opening the issue without checking all options in checklist

**Comment by itsdrnoob** [comment]
> Collapse after the issue is created using bot or use asterisk* mark 

The asterisk mark is already in use. And why use a bot for something that is not even an actual issue?

**Comment by killerrook** [comment]
Just a suggestion rest is upto you

**Comment by itsdrnoob** [comment]
> Just a suggestion rest is upto you

I do appreciate the suggestion, but I don't think it's quite necessary.
