### ISSUE TITLE
[Meta]add " I made sure that I have used appropriate descriptive title" to all templates

### ISSUE THREAD

**Issue by killerrook** [itsdrnoob/DataMonitor#71]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Is your feature request related to a problem? Please describe.

Prompts people to give the selection of appropriate title a little thought.

### Describe the solution you'd like

add " I made sure that I have used appropriate descriptive title" to all templates( bug, feature requests, questions)
