### ISSUE TITLE
[Meta] Add a question template and some way to contact(if any)

### ISSUE THREAD

**Issue by killerrook** [itsdrnoob/DataMonitor#72]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Is your feature request related to a problem? Please describe.

Where are users supposed to ask questions?

### Describe the solution you'd like

Here is a visual example:
![Screenshot_2022-11-12-23-09-44-05](https://user-images.githubusercontent.com/28833686/201487373-3c4db0d4-ea3e-439d-8655-fd5647905d9d.png)
![Screenshot_2022-11-12-23-10-07-20](https://user-images.githubusercontent.com/28833686/201487378-dc4aefa3-e1e1-4791-b547-a75f10dc1aea.png)

**Comment by itsdrnoob** [comment]
Not an actual requirement. There is still an option to open a blank issue.
> Where are users supposed to ask questions?

There is a telegram channel created solely for this purpose.
