### ISSUE TITLE
(Meta) Request users to star and fork this project in readme.md

### ISSUE THREAD

**Issue by killerrook** [itsdrnoob/DataMonitor#87]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the Feature you'd like

The repositories are ranked based on stars and forks. Adding the following text on top of readme will improve visibility and provide more user exposure.

**If you find this repository useful please consider starring and forking this project to help the development.**

### Why do you want this feature?

Explained above.

### Additional context

Hey drnoob i got something interesting for you. Maybe consider adding this. Nah just kidding. It made me laugh today so i would love to share this koler support page with you. Have a great day. 

We, money, dont have. We, money, need. You, money, give.
You can donate with PayPal. Donate with PayPal

Or you can just buy the app from the playstore. You'll get constant updates without the need to get all the way here and download the release all by yourself and install the release all by yourself and then you realize you have a different package name so you contact me but I really don't have time for this so I update it on google play and then you realize your installer doesn't work and then you realize your whole life is like this, **miserable** and not working but then you see a point of light in the distance so you run towards and and it's the "Buy" button in the Koler's page on google play, it'l make your life easier.
